id: A42AED61C
title: Confession and Fulfilment Insert for Accumulating the Practice of Turning Back
  the Summons of the Ḍākinīs
type: translation
pechas:
- IDD48DED8
- ID3B7BE4B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:44:53.066010
  last_modified_at: 2023-01-04 12:44:53.066026
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IDD48DED8/A2CC: D11A
  ID3B7BE4B/5DC4: D11A
